// Generated by CoffeeScript 1.3.3
(function() {

  window.yat = window.yat || {};

  window.yat.NavigationViewManager = (function() {

    function _Class(model) {
      this.model = model;
      this.initialize();
      this.index = 0;
    }

    _Class.prototype.initialize = function() {
      var interval, paneWidth;
      paneWidth = 150 * (this.model.length / 2);
      this.startEnd = this.model.getStartEnd();
      interval = Math.abs(moment(this.startEnd.start).diff(this.startEnd.end, 'days'));
      return this.pixelPerDay = Math.round(paneWidth / interval);
    };

    _Class.prototype.hasRenderCandidate = function() {
      return this.index < this.model.models.length;
    };

    _Class.prototype.getNextElement = function() {
      var days, item;
      item = this.model.at(this.index++);
      days = moment(item.get('date')).diff(this.startEnd.start, 'days');
      return {
        position: days * this.pixelPerDay,
        model: item
      };
    };

    _Class.prototype.updateViewport = function(viewportPos) {
      this.viewportPos = viewportPos;
    };

    _Class.prototype.get_date_for_offset = function(offset) {
      return moment(this.startEnd.start).clone().add('days', Math.round(offset / this.pixelPerDay));
    };

    return _Class;

  })();

}).call(this);
