// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.yat = window.yat || {};

  window.yat.NavigationElementView = (function(_super) {

    __extends(_Class, _super);

    function _Class() {
      return _Class.__super__.constructor.apply(this, arguments);
    }

    _Class.prototype.tagName = 'li';

    _Class.prototype.events = {
      'click': function() {
        this.options.dispatcher.trigger('navigation_element_selected', this);
        return false;
      }
    };

    _Class.prototype.initialize = function() {
      return this.render();
    };

    _Class.prototype.render = function() {
      this.$el.append(window.yat.templates.timelineNavigationElement({
        shorttitle: this.model.get('shorttitle'),
        linkHref: '#'
      }));
      if (this.model.get('category') !== void 0) {
        return this.$el.addClass('cat-' + this.model.get('category'));
      }
    };

    _Class.prototype.width = function() {
      return this.$el.width();
    };

    return _Class;

  })(Backbone.View);

}).call(this);
