// Generated by CoffeeScript 1.3.3
(function() {

  window.yat = window.yat || {};

  window.yat.templates = {
    item: _.template('<h1><%= shorttitle %></h1><p><%= content %></p>')
  };

}).call(this);
