// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.yat = window.yat || {};

  window.yat.TimelineView = (function(_super) {

    __extends(_Class, _super);

    function _Class() {
      return _Class.__super__.constructor.apply(this, arguments);
    }

    _Class.prototype.initialize = function() {
      return this.render();
    };

    _Class.prototype.render = function() {
      var that;
      that = this;
      this.container = $(window.yat.templates.timelineContainer());
      this.viewportContainer = $(window.yat.templates.timelineViewport());
      this.viewport = new window.yat.ViewportView({
        model: this.model
      });
      this.viewportContainer.append(this.viewport.$el);
      this.navigation = $(window.yat.templates.timelineNavigation());
      this.overview = new window.yat.OverviewView({
        model: this.model.getStartEnd()
      });
      this.navigationBar = new window.yat.NavigationView({
        model: this.model
      });
      this.navigation.append(this.overview.$el);
      this.navigation.append(this.navigationBar.$el);
      this.container.children('.yat-timeline-inner1').append(this.navigation);
      this.container.children('.yat-timeline-inner1').append(this.viewportContainer);
      return that.$el.append(this.container);
    };

    return _Class;

  })(Backbone.View);

}).call(this);
