// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.yat = window.yat || {};

  window.yat.ViewportView = (function(_super) {

    __extends(_Class, _super);

    function _Class() {
      return _Class.__super__.constructor.apply(this, arguments);
    }

    _Class.prototype.className = 'yat-viewport';

    _Class.prototype.next_index = 0;

    _Class.prototype.total_index = 0;

    _Class.prototype.options = {
      animation_duration: 200,
      initial_element_count: 4,
      id_prefix: ''
    };

    _Class.prototype.initialize = function() {
      return this.render();
    };

    _Class.prototype.remove = function() {
      return Backbone.View.prototype.remove.call(this);
    };

    _Class.prototype.render = function() {
      var navlinks, that, viewport;
      that = this;
      viewport = $(window.yat.templates.timelineViewportElementList());
      navlinks = $(window.yat.templates.timelineViewportNavlinks());
      this.$el.html(viewport);
      this.$el.append(navlinks);
      this.total_index = this.model.length;
      setTimeout((function() {
        that.$el.find('ol.yat-elements').css('width', 0);
        return _.times(that.options.initial_element_count, (function() {
          return that.insert_next_element();
        }));
      }), 10);
      return this.registerEventListener();
    };

    _Class.prototype.registerEventListener = function() {
      var that;
      that = this;
      this.$el.find('> .yat-inner').bind('touchmove', function() {
        return that.options.dispatcher.trigger('viewport_position_change');
      });
      this.$el.find('> .yat-inner').scroll(function() {
        return that.options.dispatcher.trigger('viewport_position_change');
      });
      this.$el.find('> .yat-inner').bind('scrollstart', function() {
        return that.options.dispatcher.trigger('viewport_scrollstart');
      });
      this.$el.find('> .yat-inner').bind('scrollstop', function() {
        return that.options.dispatcher.trigger('viewport_scrollstop', that.getCurrentElementModels());
      });
      this.$el.find('.yat-navlinks .yat-left a').click(function() {
        that.options.dispatcher.trigger('viewport_prev');
        return that.options.dispatcher.trigger('viewport_item_deselect');
      });
      this.$el.find('.yat-navlinks .yat-right a').click(function() {
        that.options.dispatcher.trigger('viewport_next');
        return that.options.dispatcher.trigger('viewport_item_deselect');
      });
      that.options.dispatcher.on('viewport_jump_to', function() {
        return that.jump_to(arguments[0], arguments[1]);
      });
      that.options.dispatcher.on('viewport_prev', function() {
        return that.options.dispatcher.trigger('viewport_jump_to', _.first(that.getCurrentElements()).prev());
      });
      that.options.dispatcher.on('viewport_next', function() {
        return that.options.dispatcher.trigger('viewport_jump_to', _.last(that.getCurrentElements()).next());
      });
      that.options.dispatcher.on('viewport_item_select', function() {
        return that.open_element(arguments[0]);
      });
      that.options.dispatcher.on('viewport_item_deselect', function() {
        return that.close_open_element(arguments[0]);
      });
      return that.options.dispatcher.on('viewport_position_change', function() {
        return that.load_more();
      });
    };

    _Class.prototype.getCurrentElements = function() {
      var current_elements, scroll_l, scroll_r;
      scroll_l = this.$el.find('> .yat-inner').scrollLeft();
      scroll_r = scroll_l + this.$el.find('> .yat-inner').width();
      current_elements = [];
      this.$el.find('ol.yat-elements').children().each(function() {
        var el_width;
        el_width = $(this).outerWidth() + parseInt($(this).css('margin-left'), 10) + parseInt($(this).css('margin-right'), 10);
        if ($(this).position().left >= scroll_l && ($(this).position().left + el_width) <= scroll_r) {
          current_elements.push($(this));
        }
        if ($(this).position().left > scroll_r) {
          return false;
        }
      });
      return current_elements;
    };

    _Class.prototype.getCurrentElementModels = function() {
      var elements, that;
      that = this;
      elements = [];
      _.each(this.getCurrentElements(), (function(element) {
        return elements.push({
          dom: element,
          model: that.model.get(element.attr('id').substr(that.options.id_prefix.length))
        });
      }));
      return elements;
    };

    _Class.prototype.insert_next_element = function() {
      var element, element_view, last, model, that;
      that = this;
      model = this.model.at(this.next_index);
      element_view = new window.yat.viewportItemView({
        model: model
      });
      element = this.$el.find('ol.yat-elements').append(element_view.$el);
      last = element.children().last();
      last.attr('id', this.options.id_prefix + model.cid);
      this.change_list_width(this.element_width(last));
      last.click(function() {
        if ($(this).hasClass('open')) {
          return that.options.dispatcher.trigger('viewport_item_deselect');
        } else {
          return that.options.dispatcher.trigger('viewport_item_select', $(this));
        }
      });
      return this.next_index++;
    };

    _Class.prototype.load_more = function() {
      var that;
      if ((this.next_index + 1) < this.total_index) {
        that = this;
        return setTimeout((function() {
          return that.insert_next_element();
        }), 10);
      }
    };

    _Class.prototype.jump_to = function() {
      var container_width, element_width;
      if (arguments[0][0] !== void 0) {
        container_width = this.$el.find('> .yat-inner').outerWidth();
        element_width = arguments[0].outerWidth() + parseInt(arguments[0].css("margin-left"), 10) + parseInt(arguments[0].css("margin-right"), 10);
        return this.$el.find('> .yat-inner').animate({
          scrollLeft: arguments[0].position().left - (container_width / 2 - element_width / 2)
        }, {
          duration: this.options.animation_duration
        });
      }
    };

    _Class.prototype.open_element = function() {
      var element, new_element_width, old_element_width, that;
      that = this;
      this.close_open_element();
      element = arguments[0];
      old_element_width = this.element_width(element);
      element.addClass('open');
      new_element_width = this.element_width(element);
      this.change_list_width(new_element_width - old_element_width, true);
      return this.options.dispatcher.trigger('viewport_jump_to', element);
    };

    _Class.prototype.close_open_element = function() {
      var element, new_element_width, old_element_width, that;
      that = this;
      if (this.$el.find('ol.yat-elements li.open').length > 0) {
        element = this.$el.find('ol.yat-elements li.open').first();
        old_element_width = this.element_width(element);
        this.$el.find('ol.yat-elements li.open').removeClass('open');
        new_element_width = this.element_width(element);
        return this.change_list_width(new_element_width - old_element_width, true);
      }
    };

    _Class.prototype.element_width = function(element) {
      return element.outerWidth() + parseInt(element.css('margin-left'), 10) + parseInt(element.css('margin-right'), 10);
    };

    _Class.prototype.change_list_width = function(width) {
      width = parseInt(this.$el.find('ol.yat-elements').css('width'), 10) + width;
      return this.$el.find('ol.yat-elements').css('width', width);
    };

    return _Class;

  })(Backbone.View);

}).call(this);
